### ISSUE TITLE
Bugs from Josaih Nyarega Review

### ISSUE THREAD

**Issue by dmigwi** [dmigwi/class-management-system#21]
Feedback copied from a LinkedIn DM
```
Hey Migwi, apologies for the delayed response. I have been quite busy lately. I hope you are doing well.

The app looks great, and thank you for implementing my feedback.

I have reviewed the application and identified some potential areas for improvement:

1. When ending a session as an instructor, I encounter an exception. [Screenshot attached]

2. When updating a unit as an administrator, the start and end dates are not displayed on the date inputs. [Screenshot]

3. Do we need a package.json file in the root directory?


By the way, I like the design. It's simple and straight to the point. It can be tempting to add advanced features like Websockets or Ajax to the application.
I like this approach because it helps us to solve the current problem without expanding the scope.(Edited)
```

![updating a unit](https://github.com/dmigwi/class-management-system/assets/22055953/e5b21c49-c7e4-40cb-a840-66636025cdbe)
![ending a session](https://github.com/dmigwi/class-management-system/assets/22055953/0dc07bda-b38c-4abb-bef0-969cc870492d)

**Comment by dmigwi** [comment]
About the update_at issues, I will fix it. Thanks for catching that bug!

>When updating a unit as an administrator, the start and end dates are not displayed on the date inputs.

`Administrator` is not an actual unit that can be taught. It is considered to be special and is only necessary in the context of the chat interface.
When Students or Instructors want to send a message to the administrator for assistance, the messages they sent are tied to the administrator unit. The administrator unit can be managed by many people therefore there is no need to update any more details about the admin details since it doesn't count as an actual course/unit taught.

>Do we need a package.json file in the root directory?

definitely not necessary. Will drop it.

**Comment by dmigwi** [comment]
I am unable to recreate issue:
`When ending a session as an instructor, I encounter an exception.`

**Comment by jmnyarega** [comment]
> I am unable to recreate issue: `When ending a session as an instructor, I encounter an exception.`

I think you solved this here https://github.com/dmigwi/class-management-system/pull/22/files#diff-ce3847ed0e55b16c5f13a3072ce6e75ae78e4718d410941963fc49b37bb5ebf7R13

by adding this line:

```php 
  // Prevents the auto filling of the update_at column.
  const UPDATED_AT = null;
```

The exception was thrown because the timestamp fields are not present in the [Timer Model](app/Models/Timer.php).

**Comment by dmigwi** [comment]
Perfect! then this issue will be closed since it has now been resolved fully!
